-- ============================================================
-- Tahajji — Curriculum (généré par scripts/build_curriculum.mjs).
-- Méthode : « La mine des novices pour la lecture du saint Coran » (RECI, Bamako),
-- utilisée avec l'autorisation de l'auteur, fusionnée avec la Qaïda Nourania.
-- Niveaux 1-5 détaillés (curriculum complet).
-- À exécuter APRÈS 0001_init.sql. (Le Coran : voir import_quran.sql.)
-- ⚠️ Re-truncate : réinitialise la progression utilisateur (dev).
-- ⚠️ EFFACE l'audio des leçons (lesson_items.audio_url remis à null) :
--    APRÈS ce script, RELANCE db/audio_lessons.sql pour rebrancher les sons.
-- ⚠️ Contenu à FAIRE VALIDER par une autorité avant publication.
-- ============================================================

truncate table quiz_questions, lesson_items, lessons, levels restart identity cascade;

insert into levels (id, position, title, description, is_premium) values
  (1, 1, 'L’alphabet — la voyelle « a »', 'Les 28 lettres lues avec la fatha (a), dans l’ordre de la méthode.', false),
  (2, 3, 'Les voyelles brèves', 'La kasra (i), la dhômma (ou) et le soukoûne.', true),
  (3, 4, 'Les voyelles longues (madd)', 'Allongement de la voyelle par Alif, Yâ et Wâw.', true),
  (4, 5, 'Le tanwîn', 'Les doubles voyelles en fin de mot : -an, -in, -oun.', true),
  (6, 2, 'Les chiffres arabes', 'Lire les chiffres ٠ à ٩.', false),
  (5, 6, 'Règles de lecture', 'Chadda, alif maqsoura, hamzatoul wasl, lettres solaires/lunaires et versets.', true);

insert into lessons (id, level_id, position, title, lesson_type, is_premium) values
  (1, 1, 1, 'Alif · Bā · Tā · Thā', 'learn', false),
  (2, 1, 2, 'Jīm · Ḥā · Khā · Dāl', 'learn', false),
  (3, 1, 3, 'Dhāl · Rā · Zāy · Sīn', 'learn', false),
  (4, 1, 4, 'Shīn · Ṣād · Ḍād · Ṭā', 'learn', false),
  (5, 1, 5, 'Ẓā · ʿAyn · Ghayn · Fā', 'learn', false),
  (6, 1, 6, 'Qāf · Kāf · Lām · Mīm', 'learn', false),
  (7, 1, 7, 'Nūn · Hā · Wāw · Yā', 'learn', false),
  (8, 1, 8, 'Examen — l’alphabet', 'exam', false),
  (9, 2, 1, 'Kasra (i) · 1', 'learn', false),
  (10, 2, 2, 'Kasra (i) · 2', 'learn', false),
  (11, 2, 3, 'Kasra (i) · 3', 'learn', false),
  (12, 2, 4, 'Kasra (i) · 4', 'learn', false),
  (13, 2, 5, 'Dhômma (ou) · 1', 'learn', false),
  (14, 2, 6, 'Dhômma (ou) · 2', 'learn', false),
  (15, 2, 7, 'Dhômma (ou) · 3', 'learn', false),
  (16, 2, 8, 'Dhômma (ou) · 4', 'learn', false),
  (17, 2, 9, 'Le soukoûne', 'learn', false),
  (18, 2, 10, 'Examen — voyelles brèves', 'exam', false),
  (19, 3, 1, 'Madd par Alif (â)', 'learn', false),
  (20, 3, 2, 'Madd par Yâ (î)', 'learn', false),
  (21, 3, 3, 'Madd par Wâw (oû)', 'learn', false),
  (22, 3, 4, 'Examen — voyelles longues', 'exam', false),
  (23, 4, 1, 'Tanwîn fatha (-an)', 'learn', false),
  (24, 4, 2, 'Tanwîn kasra (-in)', 'learn', false),
  (25, 4, 3, 'Tanwîn dhômma (-oun)', 'learn', false),
  (26, 4, 4, 'Examen — tanwîn', 'exam', false),
  (27, 6, 1, 'Les chiffres ٠–٤', 'learn', false),
  (28, 6, 2, 'Les chiffres ٥–٩', 'learn', false),
  (29, 6, 3, 'Examen — les chiffres', 'exam', false),
  (30, 5, 1, 'La chadda', 'learn', true),
  (31, 5, 2, 'Alif maqsoura (ى)', 'learn', true),
  (32, 5, 3, 'Hamzatoul wasl (ٱ)', 'learn', true),
  (33, 5, 4, 'Solaires & lunaires', 'learn', true),
  (34, 5, 5, 'Lecture de versets', 'learn', true),
  (35, 5, 6, 'Examen — règles', 'exam', true);

insert into lesson_items (id, lesson_id, position, item_type, arabic_text, transliteration, translation_fr, audio_url) values
  (1, 1, 1, 'letter', 'أَ', 'a', 'Lettre Alif / Hamza — son « a »', null),
  (2, 1, 2, 'letter', 'بَ', 'ba', 'Lettre Bā — son « ba »', null),
  (3, 1, 3, 'letter', 'تَ', 'ta', 'Lettre Tā — son « ta »', null),
  (4, 1, 4, 'letter', 'ثَ', 'tha', 'Lettre Thā — son « tha »', null),
  (5, 2, 1, 'letter', 'جَ', 'ja', 'Lettre Jīm — son « ja »', null),
  (6, 2, 2, 'letter', 'حَ', 'ḥa', 'Lettre Ḥā — son « ḥa »', null),
  (7, 2, 3, 'letter', 'خَ', 'kha', 'Lettre Khā — son « kha »', null),
  (8, 2, 4, 'letter', 'دَ', 'da', 'Lettre Dāl — son « da »', null),
  (9, 3, 1, 'letter', 'ذَ', 'dha', 'Lettre Dhāl — son « dha »', null),
  (10, 3, 2, 'letter', 'رَ', 'ra', 'Lettre Rā — son « ra »', null),
  (11, 3, 3, 'letter', 'زَ', 'za', 'Lettre Zāy — son « za »', null),
  (12, 3, 4, 'letter', 'سَ', 'sa', 'Lettre Sīn — son « sa »', null),
  (13, 4, 1, 'letter', 'شَ', 'cha', 'Lettre Shīn — son « cha »', null),
  (14, 4, 2, 'letter', 'صَ', 'ṣa', 'Lettre Ṣād — son « ṣa »', null),
  (15, 4, 3, 'letter', 'ضَ', 'ḍa', 'Lettre Ḍād — son « ḍa »', null),
  (16, 4, 4, 'letter', 'طَ', 'ṭa', 'Lettre Ṭā — son « ṭa »', null),
  (17, 5, 1, 'letter', 'ظَ', 'ẓa', 'Lettre Ẓā — son « ẓa »', null),
  (18, 5, 2, 'letter', 'عَ', 'ʿa', 'Lettre ʿAyn — son « ʿa »', null),
  (19, 5, 3, 'letter', 'غَ', 'gha', 'Lettre Ghayn — son « gha »', null),
  (20, 5, 4, 'letter', 'فَ', 'fa', 'Lettre Fā — son « fa »', null),
  (21, 6, 1, 'letter', 'قَ', 'qa', 'Lettre Qāf — son « qa »', null),
  (22, 6, 2, 'letter', 'كَ', 'ka', 'Lettre Kāf — son « ka »', null),
  (23, 6, 3, 'letter', 'لَ', 'la', 'Lettre Lām — son « la »', null),
  (24, 6, 4, 'letter', 'مَ', 'ma', 'Lettre Mīm — son « ma »', null),
  (25, 7, 1, 'letter', 'نَ', 'na', 'Lettre Nūn — son « na »', null),
  (26, 7, 2, 'letter', 'هَ', 'ha', 'Lettre Hā — son « ha »', null),
  (27, 7, 3, 'letter', 'وَ', 'wa', 'Lettre Wāw — son « wa »', null),
  (28, 7, 4, 'letter', 'يَ', 'ya', 'Lettre Yā — son « ya »', null),
  (29, 9, 1, 'letter', 'إِ', 'i', 'Lettre Alif / Hamza — son « i »', null),
  (30, 9, 2, 'letter', 'بِ', 'bi', 'Lettre Bā — son « bi »', null),
  (31, 9, 3, 'letter', 'تِ', 'ti', 'Lettre Tā — son « ti »', null),
  (32, 9, 4, 'letter', 'ثِ', 'thi', 'Lettre Thā — son « thi »', null),
  (33, 9, 5, 'letter', 'جِ', 'ji', 'Lettre Jīm — son « ji »', null),
  (34, 9, 6, 'letter', 'حِ', 'ḥi', 'Lettre Ḥā — son « ḥi »', null),
  (35, 9, 7, 'letter', 'خِ', 'khi', 'Lettre Khā — son « khi »', null),
  (36, 10, 1, 'letter', 'دِ', 'di', 'Lettre Dāl — son « di »', null),
  (37, 10, 2, 'letter', 'ذِ', 'dhi', 'Lettre Dhāl — son « dhi »', null),
  (38, 10, 3, 'letter', 'رِ', 'ri', 'Lettre Rā — son « ri »', null),
  (39, 10, 4, 'letter', 'زِ', 'zi', 'Lettre Zāy — son « zi »', null),
  (40, 10, 5, 'letter', 'سِ', 'si', 'Lettre Sīn — son « si »', null),
  (41, 10, 6, 'letter', 'شِ', 'chi', 'Lettre Shīn — son « chi »', null),
  (42, 10, 7, 'letter', 'صِ', 'ṣi', 'Lettre Ṣād — son « ṣi »', null),
  (43, 11, 1, 'letter', 'ضِ', 'ḍi', 'Lettre Ḍād — son « ḍi »', null),
  (44, 11, 2, 'letter', 'طِ', 'ṭi', 'Lettre Ṭā — son « ṭi »', null),
  (45, 11, 3, 'letter', 'ظِ', 'ẓi', 'Lettre Ẓā — son « ẓi »', null),
  (46, 11, 4, 'letter', 'عِ', 'ʿi', 'Lettre ʿAyn — son « ʿi »', null),
  (47, 11, 5, 'letter', 'غِ', 'ghi', 'Lettre Ghayn — son « ghi »', null),
  (48, 11, 6, 'letter', 'فِ', 'fi', 'Lettre Fā — son « fi »', null),
  (49, 11, 7, 'letter', 'قِ', 'qi', 'Lettre Qāf — son « qi »', null),
  (50, 12, 1, 'letter', 'كِ', 'ki', 'Lettre Kāf — son « ki »', null),
  (51, 12, 2, 'letter', 'لِ', 'li', 'Lettre Lām — son « li »', null),
  (52, 12, 3, 'letter', 'مِ', 'mi', 'Lettre Mīm — son « mi »', null),
  (53, 12, 4, 'letter', 'نِ', 'ni', 'Lettre Nūn — son « ni »', null),
  (54, 12, 5, 'letter', 'هِ', 'hi', 'Lettre Hā — son « hi »', null),
  (55, 12, 6, 'letter', 'وِ', 'wi', 'Lettre Wāw — son « wi »', null),
  (56, 12, 7, 'letter', 'يِ', 'yi', 'Lettre Yā — son « yi »', null),
  (57, 13, 1, 'letter', 'أُ', 'ou', 'Lettre Alif / Hamza — son « ou »', null),
  (58, 13, 2, 'letter', 'بُ', 'bou', 'Lettre Bā — son « bou »', null),
  (59, 13, 3, 'letter', 'تُ', 'tou', 'Lettre Tā — son « tou »', null),
  (60, 13, 4, 'letter', 'ثُ', 'thou', 'Lettre Thā — son « thou »', null),
  (61, 13, 5, 'letter', 'جُ', 'jou', 'Lettre Jīm — son « jou »', null),
  (62, 13, 6, 'letter', 'حُ', 'ḥou', 'Lettre Ḥā — son « ḥou »', null),
  (63, 13, 7, 'letter', 'خُ', 'khou', 'Lettre Khā — son « khou »', null),
  (64, 14, 1, 'letter', 'دُ', 'dou', 'Lettre Dāl — son « dou »', null),
  (65, 14, 2, 'letter', 'ذُ', 'dhou', 'Lettre Dhāl — son « dhou »', null),
  (66, 14, 3, 'letter', 'رُ', 'rou', 'Lettre Rā — son « rou »', null),
  (67, 14, 4, 'letter', 'زُ', 'zou', 'Lettre Zāy — son « zou »', null),
  (68, 14, 5, 'letter', 'سُ', 'sou', 'Lettre Sīn — son « sou »', null),
  (69, 14, 6, 'letter', 'شُ', 'chou', 'Lettre Shīn — son « chou »', null),
  (70, 14, 7, 'letter', 'صُ', 'ṣou', 'Lettre Ṣād — son « ṣou »', null),
  (71, 15, 1, 'letter', 'ضُ', 'ḍou', 'Lettre Ḍād — son « ḍou »', null),
  (72, 15, 2, 'letter', 'طُ', 'ṭou', 'Lettre Ṭā — son « ṭou »', null),
  (73, 15, 3, 'letter', 'ظُ', 'ẓou', 'Lettre Ẓā — son « ẓou »', null),
  (74, 15, 4, 'letter', 'عُ', 'ʿou', 'Lettre ʿAyn — son « ʿou »', null),
  (75, 15, 5, 'letter', 'غُ', 'ghou', 'Lettre Ghayn — son « ghou »', null),
  (76, 15, 6, 'letter', 'فُ', 'fou', 'Lettre Fā — son « fou »', null),
  (77, 15, 7, 'letter', 'قُ', 'qou', 'Lettre Qāf — son « qou »', null),
  (78, 16, 1, 'letter', 'كُ', 'kou', 'Lettre Kāf — son « kou »', null),
  (79, 16, 2, 'letter', 'لُ', 'lou', 'Lettre Lām — son « lou »', null),
  (80, 16, 3, 'letter', 'مُ', 'mou', 'Lettre Mīm — son « mou »', null),
  (81, 16, 4, 'letter', 'نُ', 'nou', 'Lettre Nūn — son « nou »', null),
  (82, 16, 5, 'letter', 'هُ', 'hou', 'Lettre Hā — son « hou »', null),
  (83, 16, 6, 'letter', 'وُ', 'wou', 'Lettre Wāw — son « wou »', null),
  (84, 16, 7, 'letter', 'يُ', 'you', 'Lettre Yā — son « you »', null),
  (85, 17, 1, 'word', 'مِنْ', 'min', 'soukoûne sur le « n » — « de »', null),
  (86, 17, 2, 'word', 'قَدْ', 'qad', 'soukoûne sur le « d » — « déjà »', null),
  (87, 17, 3, 'word', 'هَلْ', 'hal', 'soukoûne sur le « l » — « est-ce que »', null),
  (88, 17, 4, 'word', 'كَمْ', 'kam', 'soukoûne sur le « m » — « combien »', null),
  (89, 17, 5, 'word', 'قُلْ', 'qoul', 'soukoûne sur le « l » — « dis »', null),
  (90, 17, 6, 'word', 'عَنْ', 'ʿan', 'soukoûne sur le « n » — « au sujet de »', null),
  (91, 19, 1, 'word', 'بَا', 'bâ', 'Allongement : « bâ »', null),
  (92, 19, 2, 'word', 'تَا', 'tâ', 'Allongement : « tâ »', null),
  (93, 19, 3, 'word', 'جَا', 'jâ', 'Allongement : « jâ »', null),
  (94, 19, 4, 'word', 'دَا', 'dâ', 'Allongement : « dâ »', null),
  (95, 19, 5, 'word', 'رَا', 'râ', 'Allongement : « râ »', null),
  (96, 19, 6, 'word', 'سَا', 'sâ', 'Allongement : « sâ »', null),
  (97, 19, 7, 'word', 'لَا', 'lâ', 'Allongement : « lâ »', null),
  (98, 19, 8, 'word', 'مَا', 'mâ', 'Allongement : « mâ »', null),
  (99, 19, 9, 'word', 'نَا', 'nâ', 'Allongement : « nâ »', null),
  (100, 19, 10, 'word', 'كَا', 'kâ', 'Allongement : « kâ »', null),
  (101, 20, 1, 'word', 'بِي', 'bî', 'Allongement : « bî »', null),
  (102, 20, 2, 'word', 'تِي', 'tî', 'Allongement : « tî »', null),
  (103, 20, 3, 'word', 'جِي', 'jî', 'Allongement : « jî »', null),
  (104, 20, 4, 'word', 'دِي', 'dî', 'Allongement : « dî »', null),
  (105, 20, 5, 'word', 'رِي', 'rî', 'Allongement : « rî »', null),
  (106, 20, 6, 'word', 'سِي', 'sî', 'Allongement : « sî »', null),
  (107, 20, 7, 'word', 'لِي', 'lî', 'Allongement : « lî »', null),
  (108, 20, 8, 'word', 'مِي', 'mî', 'Allongement : « mî »', null),
  (109, 20, 9, 'word', 'نِي', 'nî', 'Allongement : « nî »', null),
  (110, 20, 10, 'word', 'كِي', 'kî', 'Allongement : « kî »', null),
  (111, 21, 1, 'word', 'بُو', 'boû', 'Allongement : « boû »', null),
  (112, 21, 2, 'word', 'تُو', 'toû', 'Allongement : « toû »', null),
  (113, 21, 3, 'word', 'جُو', 'joû', 'Allongement : « joû »', null),
  (114, 21, 4, 'word', 'دُو', 'doû', 'Allongement : « doû »', null),
  (115, 21, 5, 'word', 'رُو', 'roû', 'Allongement : « roû »', null),
  (116, 21, 6, 'word', 'سُو', 'soû', 'Allongement : « soû »', null),
  (117, 21, 7, 'word', 'لُو', 'loû', 'Allongement : « loû »', null),
  (118, 21, 8, 'word', 'مُو', 'moû', 'Allongement : « moû »', null),
  (119, 21, 9, 'word', 'نُو', 'noû', 'Allongement : « noû »', null),
  (120, 21, 10, 'word', 'كُو', 'koû', 'Allongement : « koû »', null),
  (121, 23, 1, 'word', 'بًا', 'bane', 'Tanwîn : « bane »', null),
  (122, 23, 2, 'word', 'تًا', 'tane', 'Tanwîn : « tane »', null),
  (123, 23, 3, 'word', 'جًا', 'jane', 'Tanwîn : « jane »', null),
  (124, 23, 4, 'word', 'دًا', 'dane', 'Tanwîn : « dane »', null),
  (125, 23, 5, 'word', 'رًا', 'rane', 'Tanwîn : « rane »', null),
  (126, 23, 6, 'word', 'سًا', 'sane', 'Tanwîn : « sane »', null),
  (127, 23, 7, 'word', 'لًا', 'lane', 'Tanwîn : « lane »', null),
  (128, 23, 8, 'word', 'مًا', 'mane', 'Tanwîn : « mane »', null),
  (129, 23, 9, 'word', 'نًا', 'nane', 'Tanwîn : « nane »', null),
  (130, 23, 10, 'word', 'كًا', 'kane', 'Tanwîn : « kane »', null),
  (131, 24, 1, 'word', 'بٍ', 'bine', 'Tanwîn : « bine »', null),
  (132, 24, 2, 'word', 'تٍ', 'tine', 'Tanwîn : « tine »', null),
  (133, 24, 3, 'word', 'جٍ', 'jine', 'Tanwîn : « jine »', null),
  (134, 24, 4, 'word', 'دٍ', 'dine', 'Tanwîn : « dine »', null),
  (135, 24, 5, 'word', 'رٍ', 'rine', 'Tanwîn : « rine »', null),
  (136, 24, 6, 'word', 'سٍ', 'sine', 'Tanwîn : « sine »', null),
  (137, 24, 7, 'word', 'لٍ', 'line', 'Tanwîn : « line »', null),
  (138, 24, 8, 'word', 'مٍ', 'mine', 'Tanwîn : « mine »', null),
  (139, 24, 9, 'word', 'نٍ', 'nine', 'Tanwîn : « nine »', null),
  (140, 24, 10, 'word', 'كٍ', 'kine', 'Tanwîn : « kine »', null),
  (141, 25, 1, 'word', 'بٌ', 'boune', 'Tanwîn : « boune »', null),
  (142, 25, 2, 'word', 'تٌ', 'toune', 'Tanwîn : « toune »', null),
  (143, 25, 3, 'word', 'جٌ', 'joune', 'Tanwîn : « joune »', null),
  (144, 25, 4, 'word', 'دٌ', 'doune', 'Tanwîn : « doune »', null),
  (145, 25, 5, 'word', 'رٌ', 'roune', 'Tanwîn : « roune »', null),
  (146, 25, 6, 'word', 'سٌ', 'soune', 'Tanwîn : « soune »', null),
  (147, 25, 7, 'word', 'لٌ', 'loune', 'Tanwîn : « loune »', null),
  (148, 25, 8, 'word', 'مٌ', 'moune', 'Tanwîn : « moune »', null),
  (149, 25, 9, 'word', 'نٌ', 'noune', 'Tanwîn : « noune »', null),
  (150, 25, 10, 'word', 'كٌ', 'koune', 'Tanwîn : « koune »', null),
  (151, 27, 1, 'word', '٠', 'sifr', '0 — صِفْر', null),
  (152, 27, 2, 'word', '١', 'wâḥid', '1 — وَاحِد', null),
  (153, 27, 3, 'word', '٢', 'ithnân', '2 — اثْنَان', null),
  (154, 27, 4, 'word', '٣', 'thalâtha', '3 — ثَلَاثَة', null),
  (155, 27, 5, 'word', '٤', 'arbaʿa', '4 — أَرْبَعَة', null),
  (156, 28, 1, 'word', '٥', 'khamsa', '5 — خَمْسَة', null),
  (157, 28, 2, 'word', '٦', 'sitta', '6 — سِتَّة', null),
  (158, 28, 3, 'word', '٧', 'sabʿa', '7 — سَبْعَة', null),
  (159, 28, 4, 'word', '٨', 'thamâniya', '8 — ثَمَانِيَة', null),
  (160, 28, 5, 'word', '٩', 'tisʿa', '9 — تِسْعَة', null),
  (161, 30, 1, 'word', 'إِنَّ', 'inna', 'chadda sur le « n » — prolongé', null),
  (162, 30, 2, 'word', 'ثُمَّ', 'thumma', 'chadda sur le « m » — prolongé', null),
  (163, 30, 3, 'word', 'حَقَّ', 'ḥaqqa', 'chadda sur le « q »', null),
  (164, 30, 4, 'word', 'خَرَّ', 'kharra', 'chadda sur le « r »', null),
  (165, 30, 5, 'word', 'مَدَّ', 'madda', 'chadda sur le « d »', null),
  (166, 30, 6, 'word', 'ضَلَّ', 'ḍalla', 'chadda sur le « l »', null),
  (167, 31, 1, 'word', 'عَلَى', 'ʿalâ', 'le ى final se lit « â »', null),
  (168, 31, 2, 'word', 'إِلَى', 'ilâ', 'le ى final se lit « â »', null),
  (169, 31, 3, 'word', 'مُوسَى', 'mûsâ', 'le ى final se lit « â »', null),
  (170, 31, 4, 'word', 'رَمَى', 'ramâ', 'le ى final se lit « â »', null),
  (171, 32, 1, 'word', 'ٱلْحَمْدُ', 'al-ḥamdu', 'lue « a » devant un lâm', null),
  (172, 32, 2, 'word', 'ٱهْدِنَا', 'ihdinâ', 'lue « i » (3ᵉ lettre kasra/fatha)', null),
  (173, 32, 3, 'word', 'ٱنْظُرْ', 'ounẓur', 'lue « ou » (3ᵉ lettre dhômma)', null),
  (174, 32, 4, 'word', 'ٱمْشُوا', 'imchoû', 'exception : lue « i » malgré la dhômma', null),
  (175, 33, 1, 'word', 'ٱلْقَمَر', 'al-qamar', 'lunaire : on entend le « l »', null),
  (176, 33, 2, 'word', 'ٱلْأَمْر', 'al-amr', 'lunaire : on entend le « l »', null),
  (177, 33, 3, 'word', 'ٱلشَّمْس', 'ach-chams', 'solaire : le « l » disparaît, lettre redoublée', null),
  (178, 33, 4, 'word', 'ٱلرَّحْمَٰن', 'ar-raḥmân', 'solaire : le « l » disparaît', null),
  (179, 33, 5, 'word', 'ٱلصِّرَاط', 'aṣ-ṣirâṭ', 'solaire', null),
  (180, 33, 6, 'word', 'ٱلطَّيْر', 'aṭ-ṭayr', 'solaire', null),
  (181, 34, 1, 'verse', 'قُلْ هُوَ ٱللَّهُ أَحَدٌ', 'Al-Ikhlas 1', 'Dis : « Il est Allah, Unique.', null),
  (182, 34, 2, 'verse', 'ٱللَّهُ ٱلصَّمَدُ', 'Al-Ikhlas 2', 'Allah, Le Seul imploré.', null),
  (183, 34, 3, 'verse', 'لَمْ يَلِدْ وَلَمْ يُولَدْ', 'Al-Ikhlas 3', 'Il n’a pas engendré et n’a pas été engendré.', null),
  (184, 34, 4, 'verse', 'وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ', 'Al-Ikhlas 4', 'Et nul n’est égal à Lui. »', null);

insert into quiz_questions (id, lesson_id, position, question_type, prompt, arabic_text, audio_url, correct_answer, options) values
  (1, 1, 1, 'recognize_letter', 'Quelle case se lit « a » ?', 'أَ', null, 'أَ', '["أَ","إِ","أُ","حَ"]'),
  (2, 1, 2, 'recognize_letter', 'Quelle case se lit « ba » ?', 'بَ', null, 'بَ', '["بِ","بُ","خَ","بَ"]'),
  (3, 1, 3, 'recognize_letter', 'Quelle case se lit « ta » ?', 'تَ', null, 'تَ', '["تُ","دَ","تَ","تِ"]'),
  (4, 1, 4, 'recognize_letter', 'Quelle case se lit « tha » ?', 'ثَ', null, 'ثَ', '["ذَ","ثَ","ثِ","ثُ"]'),
  (5, 2, 1, 'recognize_letter', 'Quelle case se lit « ja » ?', 'جَ', null, 'جَ', '["جَ","جِ","جُ","رَ"]'),
  (6, 2, 2, 'recognize_letter', 'Quelle case se lit « ḥa » ?', 'حَ', null, 'حَ', '["حِ","حُ","زَ","حَ"]'),
  (7, 2, 3, 'recognize_letter', 'Quelle case se lit « kha » ?', 'خَ', null, 'خَ', '["خُ","سَ","خَ","خِ"]'),
  (8, 2, 4, 'recognize_letter', 'Quelle case se lit « da » ?', 'دَ', null, 'دَ', '["شَ","دَ","دِ","دُ"]'),
  (9, 3, 1, 'recognize_letter', 'Quelle case se lit « dha » ?', 'ذَ', null, 'ذَ', '["ذَ","ذِ","ذُ","صَ"]'),
  (10, 3, 2, 'recognize_letter', 'Quelle case se lit « ra » ?', 'رَ', null, 'رَ', '["رِ","رُ","ضَ","رَ"]'),
  (11, 3, 3, 'recognize_letter', 'Quelle case se lit « za » ?', 'زَ', null, 'زَ', '["زُ","طَ","زَ","زِ"]'),
  (12, 3, 4, 'recognize_letter', 'Quelle case se lit « sa » ?', 'سَ', null, 'سَ', '["ظَ","سَ","سِ","سُ"]'),
  (13, 4, 1, 'recognize_letter', 'Quelle case se lit « cha » ?', 'شَ', null, 'شَ', '["شَ","شِ","شُ","عَ"]'),
  (14, 4, 2, 'recognize_letter', 'Quelle case se lit « ṣa » ?', 'صَ', null, 'صَ', '["صِ","صُ","غَ","صَ"]'),
  (15, 4, 3, 'recognize_letter', 'Quelle case se lit « ḍa » ?', 'ضَ', null, 'ضَ', '["ضُ","فَ","ضَ","ضِ"]'),
  (16, 4, 4, 'recognize_letter', 'Quelle case se lit « ṭa » ?', 'طَ', null, 'طَ', '["قَ","طَ","طِ","طُ"]'),
  (17, 5, 1, 'recognize_letter', 'Quelle case se lit « ẓa » ?', 'ظَ', null, 'ظَ', '["ظَ","ظِ","ظُ","كَ"]'),
  (18, 5, 2, 'recognize_letter', 'Quelle case se lit « ʿa » ?', 'عَ', null, 'عَ', '["عِ","عُ","لَ","عَ"]'),
  (19, 5, 3, 'recognize_letter', 'Quelle case se lit « gha » ?', 'غَ', null, 'غَ', '["غُ","مَ","غَ","غِ"]'),
  (20, 5, 4, 'recognize_letter', 'Quelle case se lit « fa » ?', 'فَ', null, 'فَ', '["نَ","فَ","فِ","فُ"]'),
  (21, 6, 1, 'recognize_letter', 'Quelle case se lit « qa » ?', 'قَ', null, 'قَ', '["قَ","قِ","قُ","هَ"]'),
  (22, 6, 2, 'recognize_letter', 'Quelle case se lit « ka » ?', 'كَ', null, 'كَ', '["كِ","كُ","وَ","كَ"]'),
  (23, 6, 3, 'recognize_letter', 'Quelle case se lit « la » ?', 'لَ', null, 'لَ', '["لُ","يَ","لَ","لِ"]'),
  (24, 6, 4, 'recognize_letter', 'Quelle case se lit « ma » ?', 'مَ', null, 'مَ', '["أَ","مَ","مِ","مُ"]'),
  (25, 7, 1, 'recognize_letter', 'Quelle case se lit « na » ?', 'نَ', null, 'نَ', '["نَ","نِ","نُ","بَ"]'),
  (26, 7, 2, 'recognize_letter', 'Quelle case se lit « ha » ?', 'هَ', null, 'هَ', '["هِ","هُ","تَ","هَ"]'),
  (27, 7, 3, 'recognize_letter', 'Quelle case se lit « wa » ?', 'وَ', null, 'وَ', '["وُ","ثَ","وَ","وِ"]'),
  (28, 7, 4, 'recognize_letter', 'Quelle case se lit « ya » ?', 'يَ', null, 'يَ', '["جَ","يَ","يِ","يُ"]'),
  (29, 8, 1, 'recognize_letter', 'Quelle case se lit « a » ?', 'أَ', null, 'أَ', '["أَ","بَ","تَ","ثَ"]'),
  (30, 8, 2, 'recognize_letter', 'Quelle case se lit « ba » ?', 'بَ', null, 'بَ', '["تَ","ثَ","جَ","بَ"]'),
  (31, 8, 3, 'recognize_letter', 'Quelle case se lit « ta » ?', 'تَ', null, 'تَ', '["جَ","حَ","تَ","ثَ"]'),
  (32, 8, 4, 'recognize_letter', 'Quelle case se lit « tha » ?', 'ثَ', null, 'ثَ', '["خَ","ثَ","جَ","حَ"]'),
  (33, 8, 5, 'recognize_letter', 'Quelle case se lit « ja » ?', 'جَ', null, 'جَ', '["جَ","حَ","خَ","دَ"]'),
  (34, 8, 6, 'recognize_letter', 'Quelle case se lit « ḥa » ?', 'حَ', null, 'حَ', '["خَ","دَ","ذَ","حَ"]'),
  (35, 8, 7, 'recognize_letter', 'Quelle case se lit « kha » ?', 'خَ', null, 'خَ', '["ذَ","رَ","خَ","دَ"]'),
  (36, 8, 8, 'recognize_letter', 'Quelle case se lit « da » ?', 'دَ', null, 'دَ', '["زَ","دَ","ذَ","رَ"]'),
  (37, 9, 1, 'recognize_letter', 'Quelle case se lit « i » ?', 'إِ', null, 'إِ', '["إِ","أَ","أُ","حِ"]'),
  (38, 9, 2, 'recognize_letter', 'Quelle case se lit « bi » ?', 'بِ', null, 'بِ', '["بَ","بُ","خِ","بِ"]'),
  (39, 9, 3, 'recognize_letter', 'Quelle case se lit « ti » ?', 'تِ', null, 'تِ', '["تُ","دِ","تِ","تَ"]'),
  (40, 9, 4, 'recognize_letter', 'Quelle case se lit « thi » ?', 'ثِ', null, 'ثِ', '["ذِ","ثِ","ثَ","ثُ"]'),
  (41, 10, 1, 'recognize_letter', 'Quelle case se lit « di » ?', 'دِ', null, 'دِ', '["شِ","دِ","دَ","دُ"]'),
  (42, 10, 2, 'recognize_letter', 'Quelle case se lit « dhi » ?', 'ذِ', null, 'ذِ', '["ذِ","ذَ","ذُ","صِ"]'),
  (43, 10, 3, 'recognize_letter', 'Quelle case se lit « ri » ?', 'رِ', null, 'رِ', '["رَ","رُ","ضِ","رِ"]'),
  (44, 10, 4, 'recognize_letter', 'Quelle case se lit « zi » ?', 'زِ', null, 'زِ', '["زُ","طِ","زِ","زَ"]'),
  (45, 11, 1, 'recognize_letter', 'Quelle case se lit « ḍi » ?', 'ضِ', null, 'ضِ', '["ضُ","فِ","ضِ","ضَ"]'),
  (46, 11, 2, 'recognize_letter', 'Quelle case se lit « ṭi » ?', 'طِ', null, 'طِ', '["قِ","طِ","طَ","طُ"]'),
  (47, 11, 3, 'recognize_letter', 'Quelle case se lit « ẓi » ?', 'ظِ', null, 'ظِ', '["ظِ","ظَ","ظُ","كِ"]'),
  (48, 11, 4, 'recognize_letter', 'Quelle case se lit « ʿi » ?', 'عِ', null, 'عِ', '["عَ","عُ","لِ","عِ"]'),
  (49, 12, 1, 'recognize_letter', 'Quelle case se lit « ki » ?', 'كِ', null, 'كِ', '["كَ","كُ","وِ","كِ"]'),
  (50, 12, 2, 'recognize_letter', 'Quelle case se lit « li » ?', 'لِ', null, 'لِ', '["لُ","يِ","لِ","لَ"]'),
  (51, 12, 3, 'recognize_letter', 'Quelle case se lit « mi » ?', 'مِ', null, 'مِ', '["إِ","مِ","مَ","مُ"]'),
  (52, 12, 4, 'recognize_letter', 'Quelle case se lit « ni » ?', 'نِ', null, 'نِ', '["نِ","نَ","نُ","بِ"]'),
  (53, 13, 1, 'recognize_letter', 'Quelle case se lit « ou » ?', 'أُ', null, 'أُ', '["أُ","أَ","إِ","حُ"]'),
  (54, 13, 2, 'recognize_letter', 'Quelle case se lit « bou » ?', 'بُ', null, 'بُ', '["بَ","بِ","خُ","بُ"]'),
  (55, 13, 3, 'recognize_letter', 'Quelle case se lit « tou » ?', 'تُ', null, 'تُ', '["تِ","دُ","تُ","تَ"]'),
  (56, 13, 4, 'recognize_letter', 'Quelle case se lit « thou » ?', 'ثُ', null, 'ثُ', '["ذُ","ثُ","ثَ","ثِ"]'),
  (57, 14, 1, 'recognize_letter', 'Quelle case se lit « dou » ?', 'دُ', null, 'دُ', '["شُ","دُ","دَ","دِ"]'),
  (58, 14, 2, 'recognize_letter', 'Quelle case se lit « dhou » ?', 'ذُ', null, 'ذُ', '["ذُ","ذَ","ذِ","صُ"]'),
  (59, 14, 3, 'recognize_letter', 'Quelle case se lit « rou » ?', 'رُ', null, 'رُ', '["رَ","رِ","ضُ","رُ"]'),
  (60, 14, 4, 'recognize_letter', 'Quelle case se lit « zou » ?', 'زُ', null, 'زُ', '["زِ","طُ","زُ","زَ"]'),
  (61, 15, 1, 'recognize_letter', 'Quelle case se lit « ḍou » ?', 'ضُ', null, 'ضُ', '["ضِ","فُ","ضُ","ضَ"]'),
  (62, 15, 2, 'recognize_letter', 'Quelle case se lit « ṭou » ?', 'طُ', null, 'طُ', '["قُ","طُ","طَ","طِ"]'),
  (63, 15, 3, 'recognize_letter', 'Quelle case se lit « ẓou » ?', 'ظُ', null, 'ظُ', '["ظُ","ظَ","ظِ","كُ"]'),
  (64, 15, 4, 'recognize_letter', 'Quelle case se lit « ʿou » ?', 'عُ', null, 'عُ', '["عَ","عِ","لُ","عُ"]'),
  (65, 16, 1, 'recognize_letter', 'Quelle case se lit « kou » ?', 'كُ', null, 'كُ', '["كَ","كِ","وُ","كُ"]'),
  (66, 16, 2, 'recognize_letter', 'Quelle case se lit « lou » ?', 'لُ', null, 'لُ', '["لِ","يُ","لُ","لَ"]'),
  (67, 16, 3, 'recognize_letter', 'Quelle case se lit « mou » ?', 'مُ', null, 'مُ', '["أُ","مُ","مَ","مِ"]'),
  (68, 16, 4, 'recognize_letter', 'Quelle case se lit « nou » ?', 'نُ', null, 'نُ', '["نُ","نَ","نِ","بُ"]'),
  (69, 17, 1, 'recognize_letter', 'Quel mot se lit « min » ?', 'مِنْ', null, 'مِنْ', '["مِنْ","قَدْ","هَلْ","كَمْ"]'),
  (70, 17, 2, 'recognize_letter', 'Quel mot se lit « qad » ?', 'قَدْ', null, 'قَدْ', '["قَدْ","هَلْ","كَمْ","قُلْ"]'),
  (71, 17, 3, 'recognize_letter', 'Quel mot se lit « hal » ?', 'هَلْ', null, 'هَلْ', '["هَلْ","كَمْ","قُلْ","عَنْ"]'),
  (72, 17, 4, 'recognize_letter', 'Quel mot se lit « kam » ?', 'كَمْ', null, 'كَمْ', '["كَمْ","قُلْ","عَنْ","مِنْ"]'),
  (73, 18, 1, 'recognize_letter', 'Quelle case se lit « ba » ?', 'بَ', null, 'بَ', '["بَ","بِ","بُ","تَ"]'),
  (74, 18, 2, 'recognize_letter', 'Quelle case se lit « bi » ?', 'بِ', null, 'بِ', '["بُ","تَ","تِ","بِ"]'),
  (75, 18, 3, 'recognize_letter', 'Quelle case se lit « bou » ?', 'بُ', null, 'بُ', '["تِ","تُ","بُ","تَ"]'),
  (76, 18, 4, 'recognize_letter', 'Quelle case se lit « ta » ?', 'تَ', null, 'تَ', '["دَ","تَ","تِ","تُ"]'),
  (77, 18, 5, 'recognize_letter', 'Quelle case se lit « ti » ?', 'تِ', null, 'تِ', '["تِ","تُ","دَ","دِ"]'),
  (78, 18, 6, 'recognize_letter', 'Quelle case se lit « tou » ?', 'تُ', null, 'تُ', '["دَ","دِ","دُ","تُ"]'),
  (79, 18, 7, 'recognize_letter', 'Quelle case se lit « da » ?', 'دَ', null, 'دَ', '["دُ","مِنْ","دَ","دِ"]'),
  (80, 18, 8, 'recognize_letter', 'Quelle case se lit « di » ?', 'دِ', null, 'دِ', '["قَدْ","دِ","دُ","مِنْ"]'),
  (81, 19, 1, 'recognize_letter', 'Quelle case se lit « bâ » (allongé) ?', 'بَا', null, 'بَا', '["بَا","بَ","تَا","جَ"]'),
  (82, 19, 2, 'recognize_letter', 'Quelle case se lit « tâ » (allongé) ?', 'تَا', null, 'تَا', '["تَ","جَا","دَ","تَا"]'),
  (83, 19, 3, 'recognize_letter', 'Quelle case se lit « jâ » (allongé) ?', 'جَا', null, 'جَا', '["دَا","رَ","جَا","جَ"]'),
  (84, 19, 4, 'recognize_letter', 'Quelle case se lit « dâ » (allongé) ?', 'دَا', null, 'دَا', '["سَ","دَا","دَ","رَا"]'),
  (85, 20, 1, 'recognize_letter', 'Quelle case se lit « bî » (allongé) ?', 'بِي', null, 'بِي', '["بِي","بِ","تِي","جِ"]'),
  (86, 20, 2, 'recognize_letter', 'Quelle case se lit « tî » (allongé) ?', 'تِي', null, 'تِي', '["تِ","جِي","دِ","تِي"]'),
  (87, 20, 3, 'recognize_letter', 'Quelle case se lit « jî » (allongé) ?', 'جِي', null, 'جِي', '["دِي","رِ","جِي","جِ"]'),
  (88, 20, 4, 'recognize_letter', 'Quelle case se lit « dî » (allongé) ?', 'دِي', null, 'دِي', '["سِ","دِي","دِ","رِي"]'),
  (89, 21, 1, 'recognize_letter', 'Quelle case se lit « boû » (allongé) ?', 'بُو', null, 'بُو', '["بُو","بُ","تُو","جُ"]'),
  (90, 21, 2, 'recognize_letter', 'Quelle case se lit « toû » (allongé) ?', 'تُو', null, 'تُو', '["تُ","جُو","دُ","تُو"]'),
  (91, 21, 3, 'recognize_letter', 'Quelle case se lit « joû » (allongé) ?', 'جُو', null, 'جُو', '["دُو","رُ","جُو","جُ"]'),
  (92, 21, 4, 'recognize_letter', 'Quelle case se lit « doû » (allongé) ?', 'دُو', null, 'دُو', '["سُ","دُو","دُ","رُو"]'),
  (93, 22, 1, 'recognize_letter', 'Quelle case se lit « bâ » ?', 'بَا', null, 'بَا', '["بَا","بِي","بُو","تَا"]'),
  (94, 22, 2, 'recognize_letter', 'Quelle case se lit « bî » ?', 'بِي', null, 'بِي', '["بُو","تَا","تِي","بِي"]'),
  (95, 22, 3, 'recognize_letter', 'Quelle case se lit « boû » ?', 'بُو', null, 'بُو', '["تِي","تُو","بُو","تَا"]'),
  (96, 22, 4, 'recognize_letter', 'Quelle case se lit « tâ » ?', 'تَا', null, 'تَا', '["جَا","تَا","تِي","تُو"]'),
  (97, 22, 5, 'recognize_letter', 'Quelle case se lit « tî » ?', 'تِي', null, 'تِي', '["تِي","تُو","جَا","جِي"]'),
  (98, 22, 6, 'recognize_letter', 'Quelle case se lit « toû » ?', 'تُو', null, 'تُو', '["جَا","جِي","جُو","تُو"]'),
  (99, 22, 7, 'recognize_letter', 'Quelle case se lit « jâ » ?', 'جَا', null, 'جَا', '["جُو","دَا","جَا","جِي"]'),
  (100, 22, 8, 'recognize_letter', 'Quelle case se lit « jî » ?', 'جِي', null, 'جِي', '["دِي","جِي","جُو","دَا"]'),
  (101, 23, 1, 'recognize_letter', 'Quelle case se lit « bane » ?', 'بًا', null, 'بًا', '["بًا","بَ","تًا","بٍ"]'),
  (102, 23, 2, 'recognize_letter', 'Quelle case se lit « tane » ?', 'تًا', null, 'تًا', '["تَ","جًا","تٍ","تًا"]'),
  (103, 23, 3, 'recognize_letter', 'Quelle case se lit « jane » ?', 'جًا', null, 'جًا', '["دًا","جٍ","جًا","جَ"]'),
  (104, 23, 4, 'recognize_letter', 'Quelle case se lit « dane » ?', 'دًا', null, 'دًا', '["دٍ","دًا","دَ","رًا"]'),
  (105, 24, 1, 'recognize_letter', 'Quelle case se lit « bine » ?', 'بٍ', null, 'بٍ', '["بٍ","بِ","تٍ","بٌ"]'),
  (106, 24, 2, 'recognize_letter', 'Quelle case se lit « tine » ?', 'تٍ', null, 'تٍ', '["تِ","جٍ","تٌ","تٍ"]'),
  (107, 24, 3, 'recognize_letter', 'Quelle case se lit « jine » ?', 'جٍ', null, 'جٍ', '["دٍ","جٌ","جٍ","جِ"]'),
  (108, 24, 4, 'recognize_letter', 'Quelle case se lit « dine » ?', 'دٍ', null, 'دٍ', '["دٌ","دٍ","دِ","رٍ"]'),
  (109, 25, 1, 'recognize_letter', 'Quelle case se lit « boune » ?', 'بٌ', null, 'بٌ', '["بٌ","بُ","تٌ","بًا"]'),
  (110, 25, 2, 'recognize_letter', 'Quelle case se lit « toune » ?', 'تٌ', null, 'تٌ', '["تُ","جٌ","تًا","تٌ"]'),
  (111, 25, 3, 'recognize_letter', 'Quelle case se lit « joune » ?', 'جٌ', null, 'جٌ', '["دٌ","جًا","جٌ","جُ"]'),
  (112, 25, 4, 'recognize_letter', 'Quelle case se lit « doune » ?', 'دٌ', null, 'دٌ', '["دًا","دٌ","دُ","رٌ"]'),
  (113, 26, 1, 'recognize_letter', 'Quelle case se lit « bane » ?', 'بًا', null, 'بًا', '["بًا","بٍ","بٌ","تًا"]'),
  (114, 26, 2, 'recognize_letter', 'Quelle case se lit « bine » ?', 'بٍ', null, 'بٍ', '["بٌ","تًا","تٍ","بٍ"]'),
  (115, 26, 3, 'recognize_letter', 'Quelle case se lit « boune » ?', 'بٌ', null, 'بٌ', '["تٍ","تٌ","بٌ","تًا"]'),
  (116, 26, 4, 'recognize_letter', 'Quelle case se lit « tane » ?', 'تًا', null, 'تًا', '["جًا","تًا","تٍ","تٌ"]'),
  (117, 26, 5, 'recognize_letter', 'Quelle case se lit « tine » ?', 'تٍ', null, 'تٍ', '["تٍ","تٌ","جًا","جٍ"]'),
  (118, 26, 6, 'recognize_letter', 'Quelle case se lit « toune » ?', 'تٌ', null, 'تٌ', '["جًا","جٍ","جٌ","تٌ"]'),
  (119, 26, 7, 'recognize_letter', 'Quelle case se lit « jane » ?', 'جًا', null, 'جًا', '["جٌ","دًا","جًا","جٍ"]'),
  (120, 26, 8, 'recognize_letter', 'Quelle case se lit « jine » ?', 'جٍ', null, 'جٍ', '["دٍ","جٍ","جٌ","دًا"]'),
  (121, 27, 1, 'recognize_letter', 'Quel chiffre est « sifr » ?', '٠', null, '٠', '["٠","١","٢","٣"]'),
  (122, 27, 2, 'recognize_letter', 'Quel chiffre est « wâḥid » ?', '١', null, '١', '["١","٢","٣","٤"]'),
  (123, 27, 3, 'recognize_letter', 'Quel chiffre est « ithnân » ?', '٢', null, '٢', '["٢","٣","٤","٠"]'),
  (124, 27, 4, 'recognize_letter', 'Quel chiffre est « thalâtha » ?', '٣', null, '٣', '["٣","٤","٠","١"]'),
  (125, 28, 1, 'recognize_letter', 'Quel chiffre est « khamsa » ?', '٥', null, '٥', '["٥","٦","٧","٨"]'),
  (126, 28, 2, 'recognize_letter', 'Quel chiffre est « sitta » ?', '٦', null, '٦', '["٦","٧","٨","٩"]'),
  (127, 28, 3, 'recognize_letter', 'Quel chiffre est « sabʿa » ?', '٧', null, '٧', '["٧","٨","٩","٥"]'),
  (128, 28, 4, 'recognize_letter', 'Quel chiffre est « thamâniya » ?', '٨', null, '٨', '["٨","٩","٥","٦"]'),
  (129, 29, 1, 'recognize_letter', 'Quelle case se lit « sifr » ?', '٠', null, '٠', '["٠","١","٢","٣"]'),
  (130, 29, 2, 'recognize_letter', 'Quelle case se lit « wâḥid » ?', '١', null, '١', '["٢","٣","٤","١"]'),
  (131, 29, 3, 'recognize_letter', 'Quelle case se lit « ithnân » ?', '٢', null, '٢', '["٤","٥","٢","٣"]'),
  (132, 29, 4, 'recognize_letter', 'Quelle case se lit « thalâtha » ?', '٣', null, '٣', '["٦","٣","٤","٥"]'),
  (133, 29, 5, 'recognize_letter', 'Quelle case se lit « arbaʿa » ?', '٤', null, '٤', '["٤","٥","٦","٧"]'),
  (134, 29, 6, 'recognize_letter', 'Quelle case se lit « khamsa » ?', '٥', null, '٥', '["٦","٧","٨","٥"]'),
  (135, 29, 7, 'recognize_letter', 'Quelle case se lit « sitta » ?', '٦', null, '٦', '["٨","٩","٦","٧"]'),
  (136, 29, 8, 'recognize_letter', 'Quelle case se lit « sabʿa » ?', '٧', null, '٧', '["٠","٧","٨","٩"]'),
  (137, 30, 1, 'recognize_letter', 'Quel mot se lit « inna » ?', 'إِنَّ', null, 'إِنَّ', '["إِنَّ","ثُمَّ","حَقَّ","خَرَّ"]'),
  (138, 30, 2, 'recognize_letter', 'Quel mot se lit « thumma » ?', 'ثُمَّ', null, 'ثُمَّ', '["ثُمَّ","حَقَّ","خَرَّ","مَدَّ"]'),
  (139, 30, 3, 'recognize_letter', 'Quel mot se lit « ḥaqqa » ?', 'حَقَّ', null, 'حَقَّ', '["حَقَّ","خَرَّ","مَدَّ","ضَلَّ"]'),
  (140, 30, 4, 'recognize_letter', 'Quel mot se lit « kharra » ?', 'خَرَّ', null, 'خَرَّ', '["خَرَّ","مَدَّ","ضَلَّ","إِنَّ"]'),
  (141, 31, 1, 'recognize_letter', 'Quel mot se lit « ʿalâ » ?', 'عَلَى', null, 'عَلَى', '["عَلَى","إِلَى","مُوسَى","رَمَى"]'),
  (142, 31, 2, 'recognize_letter', 'Quel mot se lit « ilâ » ?', 'إِلَى', null, 'إِلَى', '["إِلَى","مُوسَى","رَمَى","عَلَى"]'),
  (143, 31, 3, 'recognize_letter', 'Quel mot se lit « mûsâ » ?', 'مُوسَى', null, 'مُوسَى', '["مُوسَى","رَمَى","عَلَى","إِلَى"]'),
  (144, 31, 4, 'recognize_letter', 'Quel mot se lit « ramâ » ?', 'رَمَى', null, 'رَمَى', '["رَمَى","عَلَى","إِلَى","مُوسَى"]'),
  (145, 32, 1, 'recognize_letter', 'Quel mot se lit « al-ḥamdu » ?', 'ٱلْحَمْدُ', null, 'ٱلْحَمْدُ', '["ٱلْحَمْدُ","ٱهْدِنَا","ٱنْظُرْ","ٱمْشُوا"]'),
  (146, 32, 2, 'recognize_letter', 'Quel mot se lit « ihdinâ » ?', 'ٱهْدِنَا', null, 'ٱهْدِنَا', '["ٱهْدِنَا","ٱنْظُرْ","ٱمْشُوا","ٱلْحَمْدُ"]'),
  (147, 32, 3, 'recognize_letter', 'Quel mot se lit « ounẓur » ?', 'ٱنْظُرْ', null, 'ٱنْظُرْ', '["ٱنْظُرْ","ٱمْشُوا","ٱلْحَمْدُ","ٱهْدِنَا"]'),
  (148, 32, 4, 'recognize_letter', 'Quel mot se lit « imchoû » ?', 'ٱمْشُوا', null, 'ٱمْشُوا', '["ٱمْشُوا","ٱلْحَمْدُ","ٱهْدِنَا","ٱنْظُرْ"]'),
  (149, 33, 1, 'recognize_letter', 'Quel mot se lit « al-qamar » ?', 'ٱلْقَمَر', null, 'ٱلْقَمَر', '["ٱلْقَمَر","ٱلْأَمْر","ٱلشَّمْس","ٱلرَّحْمَٰن"]'),
  (150, 33, 2, 'recognize_letter', 'Quel mot se lit « al-amr » ?', 'ٱلْأَمْر', null, 'ٱلْأَمْر', '["ٱلْأَمْر","ٱلشَّمْس","ٱلرَّحْمَٰن","ٱلصِّرَاط"]'),
  (151, 33, 3, 'recognize_letter', 'Quel mot se lit « ach-chams » ?', 'ٱلشَّمْس', null, 'ٱلشَّمْس', '["ٱلشَّمْس","ٱلرَّحْمَٰن","ٱلصِّرَاط","ٱلطَّيْر"]'),
  (152, 33, 4, 'recognize_letter', 'Quel mot se lit « ar-raḥmân » ?', 'ٱلرَّحْمَٰن', null, 'ٱلرَّحْمَٰن', '["ٱلرَّحْمَٰن","ٱلصِّرَاط","ٱلطَّيْر","ٱلْقَمَر"]'),
  (153, 34, 1, 'recognize_letter', 'Quel verset signifie « Dis : « Il est Allah, Unique. » ?', 'قُلْ هُوَ ٱللَّهُ أَحَدٌ', null, 'قُلْ هُوَ ٱللَّهُ أَحَدٌ', '["قُلْ هُوَ ٱللَّهُ أَحَدٌ","ٱللَّهُ ٱلصَّمَدُ","لَمْ يَلِدْ وَلَمْ يُولَدْ","وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ"]'),
  (154, 34, 2, 'recognize_letter', 'Quel verset signifie « Allah, Le Seul imploré. » ?', 'ٱللَّهُ ٱلصَّمَدُ', null, 'ٱللَّهُ ٱلصَّمَدُ', '["ٱللَّهُ ٱلصَّمَدُ","لَمْ يَلِدْ وَلَمْ يُولَدْ","وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ","قُلْ هُوَ ٱللَّهُ أَحَدٌ"]'),
  (155, 34, 3, 'recognize_letter', 'Quel verset signifie « Il n’a pas engendré et n’a pas été engendré. » ?', 'لَمْ يَلِدْ وَلَمْ يُولَدْ', null, 'لَمْ يَلِدْ وَلَمْ يُولَدْ', '["لَمْ يَلِدْ وَلَمْ يُولَدْ","وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ","قُلْ هُوَ ٱللَّهُ أَحَدٌ","ٱللَّهُ ٱلصَّمَدُ"]'),
  (156, 34, 4, 'recognize_letter', 'Quel verset signifie « Et nul n’est égal à Lui. » » ?', 'وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ', null, 'وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ', '["وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ","قُلْ هُوَ ٱللَّهُ أَحَدٌ","ٱللَّهُ ٱلصَّمَدُ","لَمْ يَلِدْ وَلَمْ يُولَدْ"]'),
  (157, 35, 1, 'recognize_letter', 'Quelle case se lit « inna » ?', 'إِنَّ', null, 'إِنَّ', '["إِنَّ","ثُمَّ","حَقَّ","مَدَّ"]'),
  (158, 35, 2, 'recognize_letter', 'Quelle case se lit « thumma » ?', 'ثُمَّ', null, 'ثُمَّ', '["حَقَّ","مَدَّ","عَلَى","ثُمَّ"]'),
  (159, 35, 3, 'recognize_letter', 'Quelle case se lit « ḥaqqa » ?', 'حَقَّ', null, 'حَقَّ', '["عَلَى","إِلَى","حَقَّ","مَدَّ"]'),
  (160, 35, 4, 'recognize_letter', 'Quelle case se lit « madda » ?', 'مَدَّ', null, 'مَدَّ', '["مُوسَى","مَدَّ","عَلَى","إِلَى"]'),
  (161, 35, 5, 'recognize_letter', 'Quelle case se lit « ʿalâ » ?', 'عَلَى', null, 'عَلَى', '["عَلَى","إِلَى","مُوسَى","ٱلْقَمَر"]'),
  (162, 35, 6, 'recognize_letter', 'Quelle case se lit « ilâ » ?', 'إِلَى', null, 'إِلَى', '["مُوسَى","ٱلْقَمَر","ٱلشَّمْس","إِلَى"]'),
  (163, 35, 7, 'recognize_letter', 'Quelle case se lit « mûsâ » ?', 'مُوسَى', null, 'مُوسَى', '["ٱلشَّمْس","ٱلرَّحْمَٰن","مُوسَى","ٱلْقَمَر"]'),
  (164, 35, 8, 'recognize_letter', 'Quelle case se lit « al-qamar » ?', 'ٱلْقَمَر', null, 'ٱلْقَمَر', '["إِنَّ","ٱلْقَمَر","ٱلشَّمْس","ٱلرَّحْمَٰن"]');

select setval(pg_get_serial_sequence('levels', 'id'),         (select max(id) from levels));
select setval(pg_get_serial_sequence('lessons', 'id'),        (select max(id) from lessons));
select setval(pg_get_serial_sequence('lesson_items', 'id'),   (select max(id) from lesson_items));
select setval(pg_get_serial_sequence('quiz_questions', 'id'), (select max(id) from quiz_questions));
