-- ============================================================
-- Tahajji — Curriculum (généré par scripts/build_curriculum.mjs).
-- Méthode : « La mine des novices pour la lecture du saint Coran » (RECI, Bamako),
-- utilisée avec l'autorisation de l'auteur, fusionnée avec la Qaïda Nourania.
-- Niveaux 1-3 détaillés ; niveaux 4-5 : placeholders.
-- À exécuter APRÈS 0001_init.sql. (Le Coran : voir import_quran.sql.)
-- ⚠️ Re-truncate : réinitialise la progression utilisateur (dev).
-- ⚠️ Contenu à FAIRE VALIDER par une autorité avant publication.
-- ============================================================

truncate table quiz_questions, lesson_items, lessons, levels restart identity cascade;

insert into levels (id, position, title, description, is_premium) values
  (1, 1, 'L’alphabet — la voyelle « a »', 'Les 28 lettres lues avec la fatha (a), dans l’ordre de la méthode.', false),
  (2, 2, 'Les voyelles brèves', 'La kasra (i), la dhômma (ou) et le soukoûne.', false),
  (3, 3, 'Les voyelles longues (madd)', 'Allongement de la voyelle par Alif, Yâ et Wâw.', false),
  (4, 4, 'Le tanwîn', 'Les doubles voyelles : -an, -in, -oun.', false),
  (5, 5, 'Règles de lecture', 'Chadda, hamzatoul wasl, lettres solaires et lunaires.', true);

insert into lessons (id, level_id, position, title, lesson_type, is_premium) values
  (1, 1, 1, 'Alif · Bā · Tā · Thā', 'learn', false),
  (2, 1, 2, 'Jīm · Ḥā · Khā · Dāl', 'learn', false),
  (3, 1, 3, 'Dhāl · Rā · Zāy · Sīn', 'learn', false),
  (4, 1, 4, 'Shīn · Ṣād · Ḍād · Ṭā', 'learn', false),
  (5, 1, 5, 'Ẓā · ʿAyn · Ghayn · Fā', 'learn', false),
  (6, 1, 6, 'Qāf · Kāf · Lām · Mīm', 'learn', false),
  (7, 1, 7, 'Nūn · Hā · Wāw · Yā', 'learn', false),
  (8, 2, 1, 'La kasra (i) — partie 1', 'learn', false),
  (9, 2, 2, 'La kasra (i) — partie 2', 'learn', false),
  (10, 2, 3, 'La kasra (i) — partie 3', 'learn', false),
  (11, 2, 4, 'La kasra (i) — partie 4', 'learn', false),
  (12, 2, 5, 'La dhômma (ou) — partie 1', 'learn', false),
  (13, 2, 6, 'La dhômma (ou) — partie 2', 'learn', false),
  (14, 2, 7, 'La dhômma (ou) — partie 3', 'learn', false),
  (15, 2, 8, 'La dhômma (ou) — partie 4', 'learn', false),
  (16, 2, 9, 'Le soukoûne', 'learn', false),
  (17, 2, 10, 'Révision des voyelles', 'exam', false),
  (18, 3, 1, 'Madd par Alif (â)', 'learn', false),
  (19, 3, 2, 'Madd par Yâ (î)', 'learn', false),
  (20, 3, 3, 'Madd par Wâw (oû)', 'learn', false),
  (21, 3, 4, 'Révision des voyelles longues', 'exam', false),
  (22, 4, 1, 'Tanwîn fatha (-an)', 'learn', false),
  (23, 4, 2, 'Tanwîn kasra (-in)', 'learn', false),
  (24, 4, 3, 'Tanwîn dhômma (-oun)', 'learn', false),
  (25, 5, 1, 'La chadda', 'learn', true),
  (26, 5, 2, 'Hamzatoul wasl', 'learn', true),
  (27, 5, 3, 'Lettres solaires et lunaires', 'learn', true),
  (28, 5, 4, 'Lecture de versets', 'learn', true);

insert into lesson_items (id, lesson_id, position, item_type, arabic_text, transliteration, translation_fr, audio_url) values
  (1, 1, 1, 'letter', 'أَ', 'a', 'Lettre Alif / Hamza — son « a »', null),
  (2, 1, 2, 'letter', 'بَ', 'ba', 'Lettre Bā — son « ba »', null),
  (3, 1, 3, 'letter', 'تَ', 'ta', 'Lettre Tā — son « ta »', null),
  (4, 1, 4, 'letter', 'ثَ', 'tha', 'Lettre Thā — son « tha »', null),
  (5, 2, 1, 'letter', 'جَ', 'ja', 'Lettre Jīm — son « ja »', null),
  (6, 2, 2, 'letter', 'حَ', 'ḥa', 'Lettre Ḥā — son « ḥa »', null),
  (7, 2, 3, 'letter', 'خَ', 'kha', 'Lettre Khā — son « kha »', null),
  (8, 2, 4, 'letter', 'دَ', 'da', 'Lettre Dāl — son « da »', null),
  (9, 3, 1, 'letter', 'ذَ', 'dha', 'Lettre Dhāl — son « dha »', null),
  (10, 3, 2, 'letter', 'رَ', 'ra', 'Lettre Rā — son « ra »', null),
  (11, 3, 3, 'letter', 'زَ', 'za', 'Lettre Zāy — son « za »', null),
  (12, 3, 4, 'letter', 'سَ', 'sa', 'Lettre Sīn — son « sa »', null),
  (13, 4, 1, 'letter', 'شَ', 'cha', 'Lettre Shīn — son « cha »', null),
  (14, 4, 2, 'letter', 'صَ', 'ṣa', 'Lettre Ṣād — son « ṣa »', null),
  (15, 4, 3, 'letter', 'ضَ', 'ḍa', 'Lettre Ḍād — son « ḍa »', null),
  (16, 4, 4, 'letter', 'طَ', 'ṭa', 'Lettre Ṭā — son « ṭa »', null),
  (17, 5, 1, 'letter', 'ظَ', 'ẓa', 'Lettre Ẓā — son « ẓa »', null),
  (18, 5, 2, 'letter', 'عَ', 'ʿa', 'Lettre ʿAyn — son « ʿa »', null),
  (19, 5, 3, 'letter', 'غَ', 'gha', 'Lettre Ghayn — son « gha »', null),
  (20, 5, 4, 'letter', 'فَ', 'fa', 'Lettre Fā — son « fa »', null),
  (21, 6, 1, 'letter', 'قَ', 'qa', 'Lettre Qāf — son « qa »', null),
  (22, 6, 2, 'letter', 'كَ', 'ka', 'Lettre Kāf — son « ka »', null),
  (23, 6, 3, 'letter', 'لَ', 'la', 'Lettre Lām — son « la »', null),
  (24, 6, 4, 'letter', 'مَ', 'ma', 'Lettre Mīm — son « ma »', null),
  (25, 7, 1, 'letter', 'نَ', 'na', 'Lettre Nūn — son « na »', null),
  (26, 7, 2, 'letter', 'هَ', 'ha', 'Lettre Hā — son « ha »', null),
  (27, 7, 3, 'letter', 'وَ', 'wa', 'Lettre Wāw — son « wa »', null),
  (28, 7, 4, 'letter', 'يَ', 'ya', 'Lettre Yā — son « ya »', null),
  (29, 8, 1, 'letter', 'إِ', 'i', 'Lettre Alif / Hamza — son « i »', null),
  (30, 8, 2, 'letter', 'بِ', 'bi', 'Lettre Bā — son « bi »', null),
  (31, 8, 3, 'letter', 'تِ', 'ti', 'Lettre Tā — son « ti »', null),
  (32, 8, 4, 'letter', 'ثِ', 'thi', 'Lettre Thā — son « thi »', null),
  (33, 8, 5, 'letter', 'جِ', 'ji', 'Lettre Jīm — son « ji »', null),
  (34, 8, 6, 'letter', 'حِ', 'ḥi', 'Lettre Ḥā — son « ḥi »', null),
  (35, 8, 7, 'letter', 'خِ', 'khi', 'Lettre Khā — son « khi »', null),
  (36, 9, 1, 'letter', 'دِ', 'di', 'Lettre Dāl — son « di »', null),
  (37, 9, 2, 'letter', 'ذِ', 'dhi', 'Lettre Dhāl — son « dhi »', null),
  (38, 9, 3, 'letter', 'رِ', 'ri', 'Lettre Rā — son « ri »', null),
  (39, 9, 4, 'letter', 'زِ', 'zi', 'Lettre Zāy — son « zi »', null),
  (40, 9, 5, 'letter', 'سِ', 'si', 'Lettre Sīn — son « si »', null),
  (41, 9, 6, 'letter', 'شِ', 'chi', 'Lettre Shīn — son « chi »', null),
  (42, 9, 7, 'letter', 'صِ', 'ṣi', 'Lettre Ṣād — son « ṣi »', null),
  (43, 10, 1, 'letter', 'ضِ', 'ḍi', 'Lettre Ḍād — son « ḍi »', null),
  (44, 10, 2, 'letter', 'طِ', 'ṭi', 'Lettre Ṭā — son « ṭi »', null),
  (45, 10, 3, 'letter', 'ظِ', 'ẓi', 'Lettre Ẓā — son « ẓi »', null),
  (46, 10, 4, 'letter', 'عِ', 'ʿi', 'Lettre ʿAyn — son « ʿi »', null),
  (47, 10, 5, 'letter', 'غِ', 'ghi', 'Lettre Ghayn — son « ghi »', null),
  (48, 10, 6, 'letter', 'فِ', 'fi', 'Lettre Fā — son « fi »', null),
  (49, 10, 7, 'letter', 'قِ', 'qi', 'Lettre Qāf — son « qi »', null),
  (50, 11, 1, 'letter', 'كِ', 'ki', 'Lettre Kāf — son « ki »', null),
  (51, 11, 2, 'letter', 'لِ', 'li', 'Lettre Lām — son « li »', null),
  (52, 11, 3, 'letter', 'مِ', 'mi', 'Lettre Mīm — son « mi »', null),
  (53, 11, 4, 'letter', 'نِ', 'ni', 'Lettre Nūn — son « ni »', null),
  (54, 11, 5, 'letter', 'هِ', 'hi', 'Lettre Hā — son « hi »', null),
  (55, 11, 6, 'letter', 'وِ', 'wi', 'Lettre Wāw — son « wi »', null),
  (56, 11, 7, 'letter', 'يِ', 'yi', 'Lettre Yā — son « yi »', null),
  (57, 12, 1, 'letter', 'أُ', 'ou', 'Lettre Alif / Hamza — son « ou »', null),
  (58, 12, 2, 'letter', 'بُ', 'bou', 'Lettre Bā — son « bou »', null),
  (59, 12, 3, 'letter', 'تُ', 'tou', 'Lettre Tā — son « tou »', null),
  (60, 12, 4, 'letter', 'ثُ', 'thou', 'Lettre Thā — son « thou »', null),
  (61, 12, 5, 'letter', 'جُ', 'jou', 'Lettre Jīm — son « jou »', null),
  (62, 12, 6, 'letter', 'حُ', 'ḥou', 'Lettre Ḥā — son « ḥou »', null),
  (63, 12, 7, 'letter', 'خُ', 'khou', 'Lettre Khā — son « khou »', null),
  (64, 13, 1, 'letter', 'دُ', 'dou', 'Lettre Dāl — son « dou »', null),
  (65, 13, 2, 'letter', 'ذُ', 'dhou', 'Lettre Dhāl — son « dhou »', null),
  (66, 13, 3, 'letter', 'رُ', 'rou', 'Lettre Rā — son « rou »', null),
  (67, 13, 4, 'letter', 'زُ', 'zou', 'Lettre Zāy — son « zou »', null),
  (68, 13, 5, 'letter', 'سُ', 'sou', 'Lettre Sīn — son « sou »', null),
  (69, 13, 6, 'letter', 'شُ', 'chou', 'Lettre Shīn — son « chou »', null),
  (70, 13, 7, 'letter', 'صُ', 'ṣou', 'Lettre Ṣād — son « ṣou »', null),
  (71, 14, 1, 'letter', 'ضُ', 'ḍou', 'Lettre Ḍād — son « ḍou »', null),
  (72, 14, 2, 'letter', 'طُ', 'ṭou', 'Lettre Ṭā — son « ṭou »', null),
  (73, 14, 3, 'letter', 'ظُ', 'ẓou', 'Lettre Ẓā — son « ẓou »', null),
  (74, 14, 4, 'letter', 'عُ', 'ʿou', 'Lettre ʿAyn — son « ʿou »', null),
  (75, 14, 5, 'letter', 'غُ', 'ghou', 'Lettre Ghayn — son « ghou »', null),
  (76, 14, 6, 'letter', 'فُ', 'fou', 'Lettre Fā — son « fou »', null),
  (77, 14, 7, 'letter', 'قُ', 'qou', 'Lettre Qāf — son « qou »', null),
  (78, 15, 1, 'letter', 'كُ', 'kou', 'Lettre Kāf — son « kou »', null),
  (79, 15, 2, 'letter', 'لُ', 'lou', 'Lettre Lām — son « lou »', null),
  (80, 15, 3, 'letter', 'مُ', 'mou', 'Lettre Mīm — son « mou »', null),
  (81, 15, 4, 'letter', 'نُ', 'nou', 'Lettre Nūn — son « nou »', null),
  (82, 15, 5, 'letter', 'هُ', 'hou', 'Lettre Hā — son « hou »', null),
  (83, 15, 6, 'letter', 'وُ', 'wou', 'Lettre Wāw — son « wou »', null),
  (84, 15, 7, 'letter', 'يُ', 'you', 'Lettre Yā — son « you »', null),
  (85, 16, 1, 'word', 'مِنْ', 'min', 'soukoûne sur le « n » — « de »', null),
  (86, 16, 2, 'word', 'قَدْ', 'qad', 'soukoûne sur le « d » — « déjà »', null),
  (87, 16, 3, 'word', 'هَلْ', 'hal', 'soukoûne sur le « l » — « est-ce que »', null),
  (88, 16, 4, 'word', 'كَمْ', 'kam', 'soukoûne sur le « m » — « combien »', null),
  (89, 16, 5, 'word', 'قُلْ', 'qoul', 'soukoûne sur le « l » — « dis »', null),
  (90, 16, 6, 'word', 'عَنْ', 'ʿan', 'soukoûne sur le « n » — « au sujet de »', null),
  (91, 17, 1, 'letter', 'بَ', 'ba', 'Se lit « ba »', null),
  (92, 17, 2, 'letter', 'بِ', 'bi', 'Se lit « bi »', null),
  (93, 17, 3, 'letter', 'بُ', 'bou', 'Se lit « bou »', null),
  (94, 17, 4, 'letter', 'تَ', 'ta', 'Se lit « ta »', null),
  (95, 17, 5, 'letter', 'تِ', 'ti', 'Se lit « ti »', null),
  (96, 17, 6, 'letter', 'تُ', 'tou', 'Se lit « tou »', null),
  (97, 18, 1, 'word', 'بَا', 'bâ', 'Allongement : « bâ »', null),
  (98, 18, 2, 'word', 'تَا', 'tâ', 'Allongement : « tâ »', null),
  (99, 18, 3, 'word', 'جَا', 'jâ', 'Allongement : « jâ »', null),
  (100, 18, 4, 'word', 'دَا', 'dâ', 'Allongement : « dâ »', null),
  (101, 18, 5, 'word', 'رَا', 'râ', 'Allongement : « râ »', null),
  (102, 18, 6, 'word', 'سَا', 'sâ', 'Allongement : « sâ »', null),
  (103, 18, 7, 'word', 'لَا', 'lâ', 'Allongement : « lâ »', null),
  (104, 18, 8, 'word', 'مَا', 'mâ', 'Allongement : « mâ »', null),
  (105, 18, 9, 'word', 'نَا', 'nâ', 'Allongement : « nâ »', null),
  (106, 18, 10, 'word', 'كَا', 'kâ', 'Allongement : « kâ »', null),
  (107, 19, 1, 'word', 'بِي', 'bî', 'Allongement : « bî »', null),
  (108, 19, 2, 'word', 'تِي', 'tî', 'Allongement : « tî »', null),
  (109, 19, 3, 'word', 'جِي', 'jî', 'Allongement : « jî »', null),
  (110, 19, 4, 'word', 'دِي', 'dî', 'Allongement : « dî »', null),
  (111, 19, 5, 'word', 'رِي', 'rî', 'Allongement : « rî »', null),
  (112, 19, 6, 'word', 'سِي', 'sî', 'Allongement : « sî »', null),
  (113, 19, 7, 'word', 'لِي', 'lî', 'Allongement : « lî »', null),
  (114, 19, 8, 'word', 'مِي', 'mî', 'Allongement : « mî »', null),
  (115, 19, 9, 'word', 'نِي', 'nî', 'Allongement : « nî »', null),
  (116, 19, 10, 'word', 'كِي', 'kî', 'Allongement : « kî »', null),
  (117, 20, 1, 'word', 'بُو', 'boû', 'Allongement : « boû »', null),
  (118, 20, 2, 'word', 'تُو', 'toû', 'Allongement : « toû »', null),
  (119, 20, 3, 'word', 'جُو', 'joû', 'Allongement : « joû »', null),
  (120, 20, 4, 'word', 'دُو', 'doû', 'Allongement : « doû »', null),
  (121, 20, 5, 'word', 'رُو', 'roû', 'Allongement : « roû »', null),
  (122, 20, 6, 'word', 'سُو', 'soû', 'Allongement : « soû »', null),
  (123, 20, 7, 'word', 'لُو', 'loû', 'Allongement : « loû »', null),
  (124, 20, 8, 'word', 'مُو', 'moû', 'Allongement : « moû »', null),
  (125, 20, 9, 'word', 'نُو', 'noû', 'Allongement : « noû »', null),
  (126, 20, 10, 'word', 'كُو', 'koû', 'Allongement : « koû »', null),
  (127, 21, 1, 'word', 'بَا', 'bâ', 'Se lit « bâ »', null),
  (128, 21, 2, 'word', 'بِي', 'bî', 'Se lit « bî »', null),
  (129, 21, 3, 'word', 'بُو', 'boû', 'Se lit « boû »', null),
  (130, 21, 4, 'word', 'نَا', 'nâ', 'Se lit « nâ »', null),
  (131, 21, 5, 'word', 'نِي', 'nî', 'Se lit « nî »', null),
  (132, 21, 6, 'word', 'نُو', 'noû', 'Se lit « noû »', null);

insert into quiz_questions (id, lesson_id, position, question_type, prompt, arabic_text, audio_url, correct_answer, options) values
  (1, 1, 1, 'recognize_letter', 'Quelle case se lit « a » ?', 'أَ', null, 'أَ', '["أَ","إِ","أُ","حَ"]'),
  (2, 1, 2, 'recognize_letter', 'Quelle case se lit « ba » ?', 'بَ', null, 'بَ', '["بِ","بُ","خَ","بَ"]'),
  (3, 1, 3, 'recognize_letter', 'Quelle case se lit « ta » ?', 'تَ', null, 'تَ', '["تُ","دَ","تَ","تِ"]'),
  (4, 1, 4, 'recognize_letter', 'Quelle case se lit « tha » ?', 'ثَ', null, 'ثَ', '["ذَ","ثَ","ثِ","ثُ"]'),
  (5, 2, 1, 'recognize_letter', 'Quelle case se lit « ja » ?', 'جَ', null, 'جَ', '["جَ","جِ","جُ","رَ"]'),
  (6, 2, 2, 'recognize_letter', 'Quelle case se lit « ḥa » ?', 'حَ', null, 'حَ', '["حِ","حُ","زَ","حَ"]'),
  (7, 2, 3, 'recognize_letter', 'Quelle case se lit « kha » ?', 'خَ', null, 'خَ', '["خُ","سَ","خَ","خِ"]'),
  (8, 2, 4, 'recognize_letter', 'Quelle case se lit « da » ?', 'دَ', null, 'دَ', '["شَ","دَ","دِ","دُ"]'),
  (9, 3, 1, 'recognize_letter', 'Quelle case se lit « dha » ?', 'ذَ', null, 'ذَ', '["ذَ","ذِ","ذُ","صَ"]'),
  (10, 3, 2, 'recognize_letter', 'Quelle case se lit « ra » ?', 'رَ', null, 'رَ', '["رِ","رُ","ضَ","رَ"]'),
  (11, 3, 3, 'recognize_letter', 'Quelle case se lit « za » ?', 'زَ', null, 'زَ', '["زُ","طَ","زَ","زِ"]'),
  (12, 3, 4, 'recognize_letter', 'Quelle case se lit « sa » ?', 'سَ', null, 'سَ', '["ظَ","سَ","سِ","سُ"]'),
  (13, 4, 1, 'recognize_letter', 'Quelle case se lit « cha » ?', 'شَ', null, 'شَ', '["شَ","شِ","شُ","عَ"]'),
  (14, 4, 2, 'recognize_letter', 'Quelle case se lit « ṣa » ?', 'صَ', null, 'صَ', '["صِ","صُ","غَ","صَ"]'),
  (15, 4, 3, 'recognize_letter', 'Quelle case se lit « ḍa » ?', 'ضَ', null, 'ضَ', '["ضُ","فَ","ضَ","ضِ"]'),
  (16, 4, 4, 'recognize_letter', 'Quelle case se lit « ṭa » ?', 'طَ', null, 'طَ', '["قَ","طَ","طِ","طُ"]'),
  (17, 5, 1, 'recognize_letter', 'Quelle case se lit « ẓa » ?', 'ظَ', null, 'ظَ', '["ظَ","ظِ","ظُ","كَ"]'),
  (18, 5, 2, 'recognize_letter', 'Quelle case se lit « ʿa » ?', 'عَ', null, 'عَ', '["عِ","عُ","لَ","عَ"]'),
  (19, 5, 3, 'recognize_letter', 'Quelle case se lit « gha » ?', 'غَ', null, 'غَ', '["غُ","مَ","غَ","غِ"]'),
  (20, 5, 4, 'recognize_letter', 'Quelle case se lit « fa » ?', 'فَ', null, 'فَ', '["نَ","فَ","فِ","فُ"]'),
  (21, 6, 1, 'recognize_letter', 'Quelle case se lit « qa » ?', 'قَ', null, 'قَ', '["قَ","قِ","قُ","هَ"]'),
  (22, 6, 2, 'recognize_letter', 'Quelle case se lit « ka » ?', 'كَ', null, 'كَ', '["كِ","كُ","وَ","كَ"]'),
  (23, 6, 3, 'recognize_letter', 'Quelle case se lit « la » ?', 'لَ', null, 'لَ', '["لُ","يَ","لَ","لِ"]'),
  (24, 6, 4, 'recognize_letter', 'Quelle case se lit « ma » ?', 'مَ', null, 'مَ', '["أَ","مَ","مِ","مُ"]'),
  (25, 7, 1, 'recognize_letter', 'Quelle case se lit « na » ?', 'نَ', null, 'نَ', '["نَ","نِ","نُ","بَ"]'),
  (26, 7, 2, 'recognize_letter', 'Quelle case se lit « ha » ?', 'هَ', null, 'هَ', '["هِ","هُ","تَ","هَ"]'),
  (27, 7, 3, 'recognize_letter', 'Quelle case se lit « wa » ?', 'وَ', null, 'وَ', '["وُ","ثَ","وَ","وِ"]'),
  (28, 7, 4, 'recognize_letter', 'Quelle case se lit « ya » ?', 'يَ', null, 'يَ', '["جَ","يَ","يِ","يُ"]'),
  (29, 8, 1, 'recognize_letter', 'Quelle case se lit « i » ?', 'إِ', null, 'إِ', '["إِ","أَ","أُ","حِ"]'),
  (30, 8, 2, 'recognize_letter', 'Quelle case se lit « bi » ?', 'بِ', null, 'بِ', '["بَ","بُ","خِ","بِ"]'),
  (31, 8, 3, 'recognize_letter', 'Quelle case se lit « ti » ?', 'تِ', null, 'تِ', '["تُ","دِ","تِ","تَ"]'),
  (32, 8, 4, 'recognize_letter', 'Quelle case se lit « thi » ?', 'ثِ', null, 'ثِ', '["ذِ","ثِ","ثَ","ثُ"]'),
  (33, 9, 1, 'recognize_letter', 'Quelle case se lit « di » ?', 'دِ', null, 'دِ', '["شِ","دِ","دَ","دُ"]'),
  (34, 9, 2, 'recognize_letter', 'Quelle case se lit « dhi » ?', 'ذِ', null, 'ذِ', '["ذِ","ذَ","ذُ","صِ"]'),
  (35, 9, 3, 'recognize_letter', 'Quelle case se lit « ri » ?', 'رِ', null, 'رِ', '["رَ","رُ","ضِ","رِ"]'),
  (36, 9, 4, 'recognize_letter', 'Quelle case se lit « zi » ?', 'زِ', null, 'زِ', '["زُ","طِ","زِ","زَ"]'),
  (37, 10, 1, 'recognize_letter', 'Quelle case se lit « ḍi » ?', 'ضِ', null, 'ضِ', '["ضُ","فِ","ضِ","ضَ"]'),
  (38, 10, 2, 'recognize_letter', 'Quelle case se lit « ṭi » ?', 'طِ', null, 'طِ', '["قِ","طِ","طَ","طُ"]'),
  (39, 10, 3, 'recognize_letter', 'Quelle case se lit « ẓi » ?', 'ظِ', null, 'ظِ', '["ظِ","ظَ","ظُ","كِ"]'),
  (40, 10, 4, 'recognize_letter', 'Quelle case se lit « ʿi » ?', 'عِ', null, 'عِ', '["عَ","عُ","لِ","عِ"]'),
  (41, 11, 1, 'recognize_letter', 'Quelle case se lit « ki » ?', 'كِ', null, 'كِ', '["كَ","كُ","وِ","كِ"]'),
  (42, 11, 2, 'recognize_letter', 'Quelle case se lit « li » ?', 'لِ', null, 'لِ', '["لُ","يِ","لِ","لَ"]'),
  (43, 11, 3, 'recognize_letter', 'Quelle case se lit « mi » ?', 'مِ', null, 'مِ', '["إِ","مِ","مَ","مُ"]'),
  (44, 11, 4, 'recognize_letter', 'Quelle case se lit « ni » ?', 'نِ', null, 'نِ', '["نِ","نَ","نُ","بِ"]'),
  (45, 12, 1, 'recognize_letter', 'Quelle case se lit « ou » ?', 'أُ', null, 'أُ', '["أُ","أَ","إِ","حُ"]'),
  (46, 12, 2, 'recognize_letter', 'Quelle case se lit « bou » ?', 'بُ', null, 'بُ', '["بَ","بِ","خُ","بُ"]'),
  (47, 12, 3, 'recognize_letter', 'Quelle case se lit « tou » ?', 'تُ', null, 'تُ', '["تِ","دُ","تُ","تَ"]'),
  (48, 12, 4, 'recognize_letter', 'Quelle case se lit « thou » ?', 'ثُ', null, 'ثُ', '["ذُ","ثُ","ثَ","ثِ"]'),
  (49, 13, 1, 'recognize_letter', 'Quelle case se lit « dou » ?', 'دُ', null, 'دُ', '["شُ","دُ","دَ","دِ"]'),
  (50, 13, 2, 'recognize_letter', 'Quelle case se lit « dhou » ?', 'ذُ', null, 'ذُ', '["ذُ","ذَ","ذِ","صُ"]'),
  (51, 13, 3, 'recognize_letter', 'Quelle case se lit « rou » ?', 'رُ', null, 'رُ', '["رَ","رِ","ضُ","رُ"]'),
  (52, 13, 4, 'recognize_letter', 'Quelle case se lit « zou » ?', 'زُ', null, 'زُ', '["زِ","طُ","زُ","زَ"]'),
  (53, 14, 1, 'recognize_letter', 'Quelle case se lit « ḍou » ?', 'ضُ', null, 'ضُ', '["ضِ","فُ","ضُ","ضَ"]'),
  (54, 14, 2, 'recognize_letter', 'Quelle case se lit « ṭou » ?', 'طُ', null, 'طُ', '["قُ","طُ","طَ","طِ"]'),
  (55, 14, 3, 'recognize_letter', 'Quelle case se lit « ẓou » ?', 'ظُ', null, 'ظُ', '["ظُ","ظَ","ظِ","كُ"]'),
  (56, 14, 4, 'recognize_letter', 'Quelle case se lit « ʿou » ?', 'عُ', null, 'عُ', '["عَ","عِ","لُ","عُ"]'),
  (57, 15, 1, 'recognize_letter', 'Quelle case se lit « kou » ?', 'كُ', null, 'كُ', '["كَ","كِ","وُ","كُ"]'),
  (58, 15, 2, 'recognize_letter', 'Quelle case se lit « lou » ?', 'لُ', null, 'لُ', '["لِ","يُ","لُ","لَ"]'),
  (59, 15, 3, 'recognize_letter', 'Quelle case se lit « mou » ?', 'مُ', null, 'مُ', '["أُ","مُ","مَ","مِ"]'),
  (60, 15, 4, 'recognize_letter', 'Quelle case se lit « nou » ?', 'نُ', null, 'نُ', '["نُ","نَ","نِ","بُ"]'),
  (61, 16, 1, 'recognize_letter', 'Quel mot se lit « min » ?', 'مِنْ', null, 'مِنْ', '["مِنْ","قَدْ","هَلْ","كَمْ"]'),
  (62, 16, 2, 'recognize_letter', 'Quel mot se lit « qad » ?', 'قَدْ', null, 'قَدْ', '["قَدْ","هَلْ","كَمْ","قُلْ"]'),
  (63, 16, 3, 'recognize_letter', 'Quel mot se lit « hal » ?', 'هَلْ', null, 'هَلْ', '["هَلْ","كَمْ","قُلْ","عَنْ"]'),
  (64, 16, 4, 'recognize_letter', 'Quel mot se lit « kam » ?', 'كَمْ', null, 'كَمْ', '["كَمْ","قُلْ","عَنْ","مِنْ"]'),
  (65, 17, 1, 'recognize_letter', 'Quelle case se lit « ba » ?', 'بَ', null, 'بَ', '["بَ","بِ","تَ","تُ"]'),
  (66, 17, 2, 'recognize_letter', 'Quelle case se lit « bi » ?', 'بِ', null, 'بِ', '["بِ","بُ","تِ","بَ"]'),
  (67, 17, 3, 'recognize_letter', 'Quelle case se lit « bou » ?', 'بُ', null, 'بُ', '["بُ","تَ","تُ","بِ"]'),
  (68, 17, 4, 'recognize_letter', 'Quelle case se lit « ta » ?', 'تَ', null, 'تَ', '["تَ","تِ","بَ","بُ"]'),
  (69, 18, 1, 'recognize_letter', 'Quelle case se lit « bâ » (allongé) ?', 'بَا', null, 'بَا', '["بَا","بَ","تَا","جَ"]'),
  (70, 18, 2, 'recognize_letter', 'Quelle case se lit « tâ » (allongé) ?', 'تَا', null, 'تَا', '["تَ","جَا","دَ","تَا"]'),
  (71, 18, 3, 'recognize_letter', 'Quelle case se lit « jâ » (allongé) ?', 'جَا', null, 'جَا', '["دَا","رَ","جَا","جَ"]'),
  (72, 18, 4, 'recognize_letter', 'Quelle case se lit « dâ » (allongé) ?', 'دَا', null, 'دَا', '["سَ","دَا","دَ","رَا"]'),
  (73, 19, 1, 'recognize_letter', 'Quelle case se lit « bî » (allongé) ?', 'بِي', null, 'بِي', '["بِي","بِ","تِي","جِ"]'),
  (74, 19, 2, 'recognize_letter', 'Quelle case se lit « tî » (allongé) ?', 'تِي', null, 'تِي', '["تِ","جِي","دِ","تِي"]'),
  (75, 19, 3, 'recognize_letter', 'Quelle case se lit « jî » (allongé) ?', 'جِي', null, 'جِي', '["دِي","رِ","جِي","جِ"]'),
  (76, 19, 4, 'recognize_letter', 'Quelle case se lit « dî » (allongé) ?', 'دِي', null, 'دِي', '["سِ","دِي","دِ","رِي"]'),
  (77, 20, 1, 'recognize_letter', 'Quelle case se lit « boû » (allongé) ?', 'بُو', null, 'بُو', '["بُو","بُ","تُو","جُ"]'),
  (78, 20, 2, 'recognize_letter', 'Quelle case se lit « toû » (allongé) ?', 'تُو', null, 'تُو', '["تُ","جُو","دُ","تُو"]'),
  (79, 20, 3, 'recognize_letter', 'Quelle case se lit « joû » (allongé) ?', 'جُو', null, 'جُو', '["دُو","رُ","جُو","جُ"]'),
  (80, 20, 4, 'recognize_letter', 'Quelle case se lit « doû » (allongé) ?', 'دُو', null, 'دُو', '["سُ","دُو","دُ","رُو"]'),
  (81, 21, 1, 'recognize_letter', 'Quelle case se lit « bâ » ?', 'بَا', null, 'بَا', '["بَا","بِي","نَا","نُو"]'),
  (82, 21, 2, 'recognize_letter', 'Quelle case se lit « bî » ?', 'بِي', null, 'بِي', '["بِي","بُو","نِي","بَا"]'),
  (83, 21, 3, 'recognize_letter', 'Quelle case se lit « boû » ?', 'بُو', null, 'بُو', '["بُو","نَا","نُو","بِي"]'),
  (84, 21, 4, 'recognize_letter', 'Quelle case se lit « nâ » ?', 'نَا', null, 'نَا', '["نَا","نِي","بَا","بُو"]');

select setval(pg_get_serial_sequence('levels', 'id'),         (select max(id) from levels));
select setval(pg_get_serial_sequence('lessons', 'id'),        (select max(id) from lessons));
select setval(pg_get_serial_sequence('lesson_items', 'id'),   (select max(id) from lesson_items));
select setval(pg_get_serial_sequence('quiz_questions', 'id'), (select max(id) from quiz_questions));
